# Generated by Django 6.1.1 on 2026-09-03 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recovery.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(default='UPI', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recommended_action',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
