# Generated by Django 4.2.7 on 2026-09-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0002_alter_auditlog_details_alter_auditlog_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer_history',
            field=models.CharField(default='Regular Customer', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_segment',
            field=models.CharField(default='Regular', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
